### PR TITLE
Fix build on Node 0.12

### PR DESCRIPTION
**Pull request by davedoesdev**

### CODE REVIEW

**Comment by stoeffel** [comment]
@davedoesdev great work :+1:. @quartzjer would be awesome if this got merged. This holds us back from updating to node v4.

**Comment by quartzjer** [comment]
:+1: :+1: :+1: :+1: wooo thanks!! sorry it took a day to merge this :)

**Comment by stoeffel** [comment]
Awesome! Thx guys! Node 4 we are coming.
// cc @adrai

**Comment by adrai** [comment]
Yay it's wonderful!

**Pull request merged**
