### PR TITLE
Adding PSS and padding options

### PR DESCRIPTION
**Pull request by quartzjer**
I'd love to get these changes from @davedoesdev and @krisb merged back into the mainline repo, there's some conflicts from the divergence now that will take a little work yet.

### CODE REVIEW

**Comment by davedoesdev** [comment]
Happy to help out. What's the best way to start?

**Comment by quartzjer** [comment]
I started merging in all the smaller pull requests last fall to get ursa up to date, but that ended up diverging too far from your fork, do you think your changes would be very hard to get back in sync and merged in here?

It might be worth waiting till there's some nan work done (#73) in case that restructures a lot too?  (I'm a nan noob so not sure the impact)

**Comment by davedoesdev** [comment]
I don't think it will be too hard. But I agree, it needs https://github.com/NodePrime/ursa/issues/73 to land first.

**Comment by davedoesdev** [comment]
Since #76 has now landed, I'll see if I can make some time to get this done.

**Comment by quartzjer** [comment]
Awesome! :+1:

**Comment by davedoesdev** [comment]
I've made a start on this but have a quick question. Currently there's this code for detecting a particular error case:

```javascript
        // Something went wrong; investigate!
        unsigned long err = ERR_peek_error();
        int lib = ERR_GET_LIB(err);
        int reason = ERR_GET_REASON(err);
        if ((lib == ERR_LIB_RSA) && (reason == RSA_R_BAD_SIGNATURE)) {
            // This just means that the signature didn't match
            // (as opposed to, say, a more dire failure in the library
            // warranting an exception throw).
            ERR_get_error(); // Consume the error (get it off the err stack).
            NanReturnValue(NanFalse());
        }
```

In my changes, I'd removed this and always throw an exception. The reason is that if e.g. padding is wrong, alg is wrong then `RSA_R_BAD_SIGNATURE` is not returned so the caller has to handle exceptions anyway.

But that would obviously change existing API behaviour so wanted to get feedback first.

**Comment by davedoesdev** [comment]
Work done on https://github.com/quartzjer/ursa/pull/80

@quartzjer please close this PR.

**Pull request closed without merging**
